version: '2'
services:
  web_server:
    image: kubeguide/tomcat-app:v1
    environment:
      MYSQL_SERVICE_HOST:mysql
      MYSQL_SERVICE_PORT:3306
  web-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    stdin_open: true
    tty: true
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  mysql-server:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD:123456
    
